### ISSUE TITLE
Warnings about style and deprecated blocks in brew

### ISSUE THREAD

**Issue by bgelens** [dapr/homebrew-tap#19]
![image](https://user-images.githubusercontent.com/10071039/114504427-269ab080-9c2f-11eb-9a3d-c05b4a2d4003.png)

**Comment by mmarquesbr** [comment]
Warning: Calling `cellar` in a bottle block is deprecated! Use `brew style --fix` on the formula to update the style or use `sha256` with a `cellar:` argument instead.
Please report this issue to the dapr/tap tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/dapr/homebrew-tap/dapr-cli.rb:17

Warning: Calling `sha256 "digest" => :tag` in a bottle block is deprecated! Use `brew style --fix` on the formula to update the style or use `sha256 tag: "digest"` instead.
Please report this issue to the dapr/tap tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/dapr/homebrew-tap/dapr-cli.rb:18

**Same here!**

**Comment by readefries** [comment]
I created a PR to fix this in the current tap and the pipelines for future releases #20

**Comment by tonidy** [comment]
Hi @readefries, your PR still give the warning. I've tried to fix with `brew style` and here is the diff:

```diff
diff --git a/dapr-cli.rb b/dapr-cli.rb
index b804b9c..c82ab66 100644
--- a/dapr-cli.rb
+++ b/dapr-cli.rb
@@ -4,20 +4,19 @@
 # ------------------------------------------------------------
 
 class DaprCli < Formula
-  desc "Client for Dapr."
+  desc "Client for Dapr"
   homepage "https://dapr.io"
-  version '1.1.0'
   url "https://github.com/dapr/cli/archive/v1.1.0.tar.gz"
+  version "1.1.0"
   sha256 "e34389a4491b071bdd915d72adaf2ee8273d0da90b4178a16c88c28ceaba2717"
 
-  depends_on "go" => :build
-
   bottle do
     root_url "https://github.com/dapr/homebrew-tap/releases/download/v1.1.0"
-    cellar :any_skip_relocation
     sha256 catalina: "818bd14f4c8b05ff249444e0e1e7b98ba5183f2342d82481709df687b8573d5d"
   end
 
+  depends_on "go" => :build
+
   def install
     system "go", "build", "-ldflags", "-X main.version=#{version} -X main.apiVersion=1.0", "-o", "./cli"
     bin.install "cli" => "dapr"
@@ -27,4 +26,3 @@ class DaprCli < Formula
     system "#{bin}/dapr", "--version"
   end
 end
-
```

**Comment by readefries** [comment]
I fixed one of the two issues, I didn't notice the other one.

As I read the [documentation](https://github.com/Homebrew/brew/blob/master/docs/Bottles.md), `cellar :any_skip_relocation` means the build doesn't refer to its own paths:

> his means that the bottle can be safely installed in any Cellar as it did not contain any references to its installation Cellar

As the line can be safely removed, I will create a PR for this.

**Comment by readefries** [comment]
Ah, not completely true. Its place has just moved.
