### ISSUE TITLE
Cannot tap dapr/tap

### ISSUE THREAD

**Issue by cecilphillip** [dapr/homebrew-tap#23]
Can't install dapr via homebrew. Below is the output returned when I run `brew install dapr/tap/dapr-cli`

<img width="1517" alt="Screen Shot 2021-06-24 at 4 08 41 PM" src="https://user-images.githubusercontent.com/350882/123325809-7ab2f280-d506-11eb-9708-3ffe4d6df26c.png">

**Comment by besteban1989** [comment]
Same error here: 
![image](https://user-images.githubusercontent.com/7503909/125692535-cf2aabe0-5379-49df-ab53-c5cf53ca38e7.png)

**Comment by artursouza** [comment]
This is fixed now. Thanks.
