### ISSUE TITLE
no release for macos montery

### ISSUE THREAD

**Issue by sker65** [dapr/homebrew-tap#35]
there is no release for newer macos version e.g. montery

**Comment by juliusbartolome** [comment]
any updates to this one?

**Comment by karrychow** [comment]
When will it be updated

**Comment by artursouza** [comment]
Homebrew does not require binaries for each OS version since it compiles from source by default. Is there any specific issue people are running into by installing on CLI on those versions?

**Comment by dserodio** [comment]
The issue is that the install fails:

```
$ brew install dapr-cli
==> Fetching dapr/tap/dapr-cli
==> Downloading https://github.com/dapr/homebrew-tap/releases/download/v1.9.1/dapr-cli-1.9.1.monterey.bottle.tar.gz
curl: (22) The requested URL returned error: 404

Error: dapr-cli: Failed to download resource "dapr-cli"
Download failed: https://github.com/dapr/homebrew-tap/releases/download/v1.9.1/dapr-cli-1.9.1.monterey.bottle.tar.gz
```

**Comment by artursouza** [comment]
OK. For some reason the Bottle's OS name got Monterey but the file says BigSur, so I am removing it to force install from source for everyone:

https://github.com/dapr/homebrew-tap/pull/36

**Comment by artursouza** [comment]
BTW, it still works on my M1 Mac with Monterey but it might be causing issues in Intel Macs (I assume).
