### ISSUE TITLE
i/o timeout

### ISSUE THREAD

**Issue by ToviHe** [dapr/homebrew-tap#38]
<img width="1417" alt="image" src="https://github.com/dapr/homebrew-tap/assets/109323790/64fc823c-1e92-47c2-8141-8209e5b8a0f8">

I am in China and this problem occurred when I installed through commands. How can I solve it?

**Comment by burhan** [comment]
You can [download the latest release](https://github.com/dapr/homebrew-tap/releases/), extract the archive, and then run the following commands

```
GOPROXY=direct make REL_VERSION=1.12.0 # replace this with the version you want to build
mv dist/*/release/dapr $HOMEBREW_PREFIX/bin/
```

This should approximate what the install process does. The formula doesn't respect the `GOPROXY` environment variables.

**Comment by burhan** [comment]
I've submitted a PR to add support for `GOPROXY` #40
